---
-
  name: Update Komerco Edge binary
  hosts:
    - all
  become: yes
  tasks:
    ## update & upgrade system
    - name: Update & upgrade system
      apt:
        upgrade: yes
        update_cache: yes

    ## stop komerco-chain service
    - name: Stop komerco edge service
      systemd:
        state: stopped
        name: komerco-chain

    ## get the latest release
    - name: Get latest release link
      uri:
        url: https://api.github.com/repos/0xKomerco/komerco-chain/releases/latest
        return_content: true
      register: edge_release

    ## download the latest release
    - name: Download latest Komerco Edge release
      get_url:
        url: "{{ edge_release.json.assets[3].browser_download_url }}"
        dest: /tmp/komerco-chain.tar.gz
        force: yes

    ## create temp dir for release
    - name: Create temp dir for Komerco Edge release
      file:
        path: /tmp/komerco-chain
        state: directory

    ## unpack release tar
    - name: Unpack Komerco Edge release
      unarchive:
        remote_src: yes
        src: /tmp/komerco-chain.tar.gz
        dest: /tmp/komerco-chain

    ## set komerco-chain to PATH
    - name: Place Komerco Edge binary to PATH
      copy:
        remote_src: yes
        src: /tmp/komerco-chain/komerco-chain
        dest: /usr/local/bin/
        mode: a+x
        force: yes

    ## remove release temp dir
    - name: Remove temp Komerco Edge release dir
      file:
        state: absent
        path: /tmp/komerco-chain

    ## start komerco edge service
    - name: Start komerco-chain service
      systemd:
        state: restarted
        name: komerco-chain
        daemon_reload: yes
        enabled: yes