---
name: Nightly Build
on:  # yamllint disable-line rule:truthy
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 0 * * *'

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml

  test:
    name: Test
    uses: ./.github/workflows/test.yml
    needs: build
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  e2e:
    name: Komerbft E2E Tests
    uses: ./.github/workflows/e2e-komerbft.yml
    needs: build

  property:
    name: Komerbft Property Tests
    uses: ./.github/workflows/property-komerbft.yml
    needs: build
  